Code refactoring in WindowsSpecification
pywinauto/pywinauto pull request #1016
Opened 2020-12-06 12:34 UTC by EOKruglov

Linked issues: 
* https://github.com/pywinauto/pywinauto/issues/710
* https://github.com/pywinauto/pywinauto/issues/807

Changes:
* rename .wrapper_object() to .find(); wrapper_object marked as deprecated; WrapperObject marked as removed
* rename .child_window() to .by(); child_window, window marked as deprecated; ChildWindow, Window, Window_, window_ marked as removed

2020-12-06 14:50 UTC, vasily-v-ryabov requested changes

2020-12-06 14:50 UTC, vasily-v-ryabov commented on apps/Gtk_samples/gtk_example.py
> +        Gtk.by.__init__(self, title="MainWindow")
Looks like wrong replace. This is not connected with the core library code.

2020-12-06 14:50 UTC, vasily-v-ryabov commented on sandbox/recorder.py
> +        wrapped = app.window(handle = event.by)
This file shouldn't be touched as well.

2021-01-28 13:34 UTC, vasily-v-ryabov approved these changes

2021-01-28 13:35 UTC, vasily-v-ryabov commented
`import warnings` is not used any more in `base_application.py`. So it can be removed.

2021-02-07 10:10 UTC, EOKruglov commented
> `import warnings` is not used any more in `base_application.py`. So it can be removed.

removed

2021-02-07 11:50 UTC, merged